---
fullscreen: false

player:
  acceleration: 0.3
  friction: 0.9
  rotation_speed: 2

game:
  max_enemies_before_game_end: 40

levelone:
  ships_destroyed_to_complete: 1
  max_num_ships_that_can_escape: 40
  enemy_frequency: 0.05
  enemy_slow_speed: 2
  enemy_fast_speed: 4
  speed_ratio: 0.5

leveltwo:
  num_asteroids_pass_to_complete: 1
  asteroid_frequency: 0.05  
  asteroid_slow_speed: 2
  asteroid_fast_speed: 4
  speed_ratio: 0.5